config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :attendances, only: [:edit, :update]
  resources :conversations, only: [:index, :show]
  resources :events
  resources :messages

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  get 'create_conversations/:id', controller: 'events', action: 'create_conversations', as: 'create_conversations'
  get 'shared_event/:code', controller: 'events', action: 'shared_event'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :first_user, class_name: 'User', foreign_key: 'first_user_id'
  belongs_to :second_user, class_name: 'User', foreign_key: 'second_user_id'
  belongs_to :event
  has_many :notifications, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  after_create_commit :create_notifications

  def create_notifications
    @user = User.find(self.first_user_id)
    @notification = Notification.create(conversation_id: self.id, user_id: @user.id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  def index
    @conversations = Conversation.all
    @notifications = current_user.notifications
    @notifications.update_all checked: true
  end

  def show
    @attendance = Attendance.find_by(event_id: @conversation.event_id, user_id: @conversation.second_user_id)
    @messages = @conversation.messages
    # Determine who is receiving the message
    if @conversation.first_user_id == current_user.id
      @message = @conversation.messages.new(sender_id: current_user.id, receiver_id: @conversation.second_user_id)
    elsif @conversation.second_user_id == current_user.id
      @message = @conversation.messages.new(sender_id: current_user.id, receiver_id: @conversation.first_user_id)
    else
      redirect_to conversations_path, alert: 'You do not have access to this conversation.'
    end
    @message.answers.new
    @message.answers.new
    @message.answers.new
    @message.answers.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class="jumbotron bg-white">
  <div class="row">
    <div class="col">
      <h1><%= fa_icon('comments') %> Chat</h1>
      <p>Here you'll find your conversations with your Secret Santas or your Giftees!</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2>My Secret Santas</h2>
      <div class="card">
        <div class="card-body p-0 table-responsive">
          <table class="table table-sm">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Event</th>
                <th scope="col"></th>
              </tr>
            </thead>

            <tbody>
              <% @conversations.each do |conversation| %>
                <% if conversation.second_user_id == current_user.id and Event.find_by(id: conversation.event_id).deadline > Time.now %>
                  <tr>
                    <% @event = Event.find(conversation.event_id) %>
                    <td><%= image_tag "new-profile3.png", height: 50, class: 'rounded-lg' %></td>
                    <td><%= @event.title %></td>
                    <td>
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Actions
                        </button>
                        <div class="dropdown-menu">
                          <%= link_to fa_icon('inbox') + ' Inbox', conversation, class: 'dropdown-item' %>
                        </div>
                      </div>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h2>My Gift Receivers</h2>
      <div class="card">
        <div class="card-body p-0 table-responsive">
          <table class="table table-sm">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Name</th>
                <th scope="col">Event</th>
                <th scope="col"></th>
              </tr>
            </thead>

            <tbody>
              <% @conversations.each do |conversation| %>
                <% if conversation.first_user_id == current_user.id and Event.find_by(id: conversation.event_id).deadline > Time.now%>
                  <tr>
                    <% @event = Event.find(conversation.event_id) %>
                    <td><%= image_tag User.find(conversation.second_user_id).image, height: 50, class: 'rounded-lg' %></td>
                    <td><%= User.find(conversation.second_user_id).name %></td>
                    <td><%= @event.title %></td>
                    <td>
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Actions
                        </button>
                        <div class="dropdown-menu">
                          <%= link_to fa_icon('inbox') + ' Inbox', conversation, class: 'dropdown-item' %>
                        </div>
                      </div>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col">
      <h2>My Past Conversations</h2>
      <div class="card">
        <div class="card-body p-0 table-responsive">
          <table class="table table-sm">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Event</th>
                <th scope="col"></th>
              </tr>
            </thead>

            <tbody>
              <% @conversations.each do |conversation| %>
                <% if Event.find_by(id: conversation.event_id).deadline < Time.now %>
                  <%if conversation.first_user_id == current_user.id %>
                    <tr>
                      <% @event = Event.find(conversation.event_id) %>
                      <td><%= image_tag User.find(conversation.second_user_id).image, height: 50, class: 'rounded-lg' %></td>
                      <td><%= @event.title %></td>
                      <td>
                        <div class="btn-group">
                          <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Actions
                          </button>
                          <div class="dropdown-menu">
                            <%= link_to fa_icon('inbox') + ' Inbox', conversation, class: 'dropdown-item' %>
                          </div>
                        </div>
                      </td>
                    </tr>
                  <% elsif conversation.second_user_id == current_user.id %>
                    <tr>
                      <% @event = Event.find(conversation.event_id) %>
                      <td><%= image_tag User.find(conversation.first_user_id).image, height: 50, class: 'rounded-lg' %></td>
                      <td><%= @event.title %></td>
                      <td>
                        <div class="btn-group">
                          <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Actions
                          </button>
                          <div class="dropdown-menu">
                            <%= link_to fa_icon('inbox') + ' Inbox', conversation, class: 'dropdown-item' %>
                            <%= link_to fa_icon('trash') + ' Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
                          </div>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="jumbotron bg-white">
  <div class="row">
    <div class="col">
      <h1><%= fa_icon('inbox') %> Inbox</h1> 
      <p>
        This inbox is to message
        <% if @conversation.first_user_id == current_user.id %>
          your <span class="text-danger">Giftee <%= User.find(@conversation.second_user_id).name %></span> from <span class="text-danger"><%= Event.find(@conversation.event_id).title %>.</span>
        <% elsif @conversation.second_user_id == current_user.id %>
          your <span class="text-danger">Secret Santa</span> from <span class="text-danger"><%= Event.find(@conversation.event_id).title %>.</span>
        <% end %>
      </p>
      <p>
        The idea is to send a question with multiple answers and the other account must select an option. Once the question is sent, you can check the answer in your 'Sent Messages' section.
      </p>
      <% if Event.find_by(id: @conversation.event_id).deadline > Time.now %>
        <% if @conversation.second_user_id == current_user.id and @attendance.user_guess_id == nil %>
          <h4>Already know who is your Secret Santa?</h4>
          <%= link_to 'Guess My Secret Santa!', edit_attendance_path(@attendance), class: 'btn btn-danger btn-lg' %>
        <% elsif @conversation.second_user_id == current_user.id and @attendance.user_guess_id != nil %>
          <%= link_to 'You have already tried to guess your Secret Santa', edit_attendance_path(@attendance), class: 'btn btn-secondary btn-lg disabled' %>  
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-md-6">
      <h2>Received Messages</h2>
      <ul class="list-group">
        <% @messages.reverse.drop(1).reverse.each do |m| %>
          <% if m.receiver_id == current_user.id %>
            <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                <a href="<%= message_path(m) %>" class="text-danger">
                  <% if m.answers.where(option: true).count > 0 %>
                    <%= fa_icon('envelope-open')%>
                  <% elsif m.answers.where(option: false).count == 4 %>
                    <%= fa_icon('envelope')%>
                  <% end %>
                  <%= m.question %>
                </a>
            </li>
          <% end %>
        <% end %>
      </ul>
      <h2>Sent Messages</h2>
      <ul class="list-group">
        <% @messages.reverse.drop(1).reverse.each do |m| %>
          <% if m.sender_id == current_user.id %>
            <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                <a href="<%= message_path(m) %>" class="text-danger">
                  <% if m.answers.where(option: true).count > 0 %>
                    <%= fa_icon('envelope-open')%>
                  <% elsif m.answers.where(option: false).count == 4 %>
                    <%= fa_icon('envelope')%>
                  <% end %>
                  <%= m.question %>
                </a>
                <span class="badge badge-pill"><%= link_to fa_icon('times'), m, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-light' %></span>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="col-md-6">
      <% if Event.find_by(id: @conversation.event_id).deadline > Time.now %>
        <h2>New Message</h2>
        <% if @conversation.second_user_id == current_user.id and @attendance.user_guess_id != nil %>
          <p>You cannot message your Secret Santa anymore.</p>
        <% elsif @conversation.first_user_id == current_user.id and @attendance.user_guess_id != nil %>
          <p>Your Giftee has tried to guess who you are.</p>
        <% else %>
          <%= form_with(model: @message, local: true) do |form| %>
            <% if @message.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
          
                <ul>
                <% @message.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <%= form.hidden_field :conversation_id, :value => @conversation.id %>
            <%= form.hidden_field :sender_id, :value => @message.sender_id %>
            <%= form.hidden_field :receiver_id, :value => @message.receiver_id %>

            <div class="form-group">
              <%= form.label :question %>
              <%= form.text_area :question, placeholder: 'What is your favorite color?', class: 'form-control' %>
            </div>
            
            <label>Options</label>
            <%= form.fields_for :answers do |a| %>
              <div class="form-group">
                <%= a.text_area :description, class: 'form-control', rows: 1, placeholder: Faker::Color.color_name %>
              </div>
            <% end %>
          
            <div class="actions">
              <%= form.submit 'Send', class: 'btn btn-danger' %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>