config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :attendances, only: [:edit, :update]
  resources :conversations, only: [:index, :show]
  resources :events
  resources :messages

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  get 'create_conversations/:id', controller: 'events', action: 'create_conversations', as: 'create_conversations'
  get 'shared_event/:code', controller: 'events', action: 'shared_event'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances, :dependent => :destroy
  has_many :conversations, :dependent => :destroy
  has_many :users, :through => :attendances, :dependent => :destroy
  belongs_to :admin, class_name: 'User', foreign_key: 'admin_id'
  after_create_commit :create_attendances
  before_create :set_access_link

  def create_attendances
    attendance_admin = Attendance.create(event_id: self.id, user_id: admin_id)
    (self.members - 1).times do |m|
      attendance = Attendance.create(event_id: self.id)
    end
  end

  def add_new_user(user)
    @attendance = self.attendances.where(user_id: nil).first
    if @attendance == nil
      false
    else
      @attendance.update!(user_id: user.id)
      true
    end
  end

  def set_access_link
    self.access_code_link = generate_code
  end

  def generate_code
    SecureRandom.hex(10)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :store_user_location!, only: [:shared_event]
  before_action :authenticate_user! 
  before_action :set_event, only: [:show, :edit, :update, :destroy, :create_attendances, :create_conversations, :delete_attendances, :delete_conversations]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    if @event.attendances.where(user_id: current_user.id).count <= 0
      redirect_to events_path, alert: 'You cannot enter this event.'
    end
    @users = User.all
    if @event.deadline < Time.now
      redirect_to events_path, alert: 'This event has finished.'
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params.merge({admin_id: current_user.id}))

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def shared_event
    @event_url = after_sign_in_path_for(:user)
    @event_url.slice! "/events/"
    @event = Event.find(@event_url.to_i)
    if @event.present?
      if @event.attendances.where(user_id: current_user).size == 0
        unless @event.add_new_user(current_user)
          redirect_to events_path, alert: 'This event is full.'
          return
        end
      end
      redirect_to @event
    else
      redirect_to events_path, alert: 'This event does not exist.'
    end
  end

  def invite_user
    @event = event
  end

  def create_conversations
    guests = @event.attendances.shuffle
    guests_rotated = guests.rotate
    pairs = guests.zip(guests_rotated)
    pairs.each do |c|
      conversation = Conversation.create(first_user_id: c[0].user_id, second_user_id: c[1].user_id, event_id: @event.id)
    end
    @event.update!(event_chat: true)
    redirect_to @event, notice: 'The Secret Santas has been succesfully distributed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def store_user_location!
      @event = Event.find_by_access_code_link(params[:code])
      # :user is the scope we are authenticating
      store_location_for(:user, url_for(@event))
    end

    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || super
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :members, :price_limit, :deadline, :admin_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit_form.html.erb
<%= form_with(model: event, local: true, class: 'form-signin') do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', rows: 3 %>
  </div>

  <%= form.hidden_field :members %>

  <div class="form-group">
    <%= form.label :price_limit %> 
    <%= form.number_field :price_limit, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :deadline %>
    <%= form.datetime_field :deadline, class: 'form-control', min: Date.today %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-danger' %>
    <%= link_to 'Back', :back, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, class: 'form-signin') do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', rows: 3 %>
  </div>

  <div class="form-group">
    <%= form.label :members %>
    <%= form.number_field :members, min: 3, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price_limit %> 
    <%= form.number_field :price_limit, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :deadline %>
    <%= form.datetime_field :deadline, class: 'form-control', min: Date.today %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-danger' %>
    <%= link_to 'Back', :back, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="col-md-6 offset-md-3 text-center jumbotron bg-white">
  <h1>Editing Event</h1>
  <%= render 'edit_form', event: @event %>
</div>

app/views/events/index.html.erb
<div class="jumbotron bg-white">
  <div class="row">
    <div class="col">
      <h1><%= fa_icon('gift') %> My Events</h1>
      <p>
        These are the events where you either created or were invited to. You can start off by clicking 'Create Event' to start your first event!
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2>Created Events <%= link_to 'Create Event', new_event_path, class: 'btn btn-danger' %></h2>
      <div class="card">
        <div class="card-body p-0 table-responsive">
          <table class="table table-sm">
            <thead>
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col"></th>
              </tr>
            </thead>

            <tbody>
              <% @events.each do |event| %>
                <% if event.admin_id == current_user.id and event.deadline > Time.now %>
                  <tr>
                    <td><%= event.title %></td>
                    <td><%= event.deadline.strftime("%B %d, %Y") %></td>
                    <td><%= event.deadline.strftime("%I:%M%p") %></td>
                    <td>
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Actions
                        </button>
                        <div class="dropdown-menu">
                          <%= link_to fa_icon('search') + ' Show', event, class: 'dropdown-item' %>
                          <%= link_to fa_icon('edit') + ' Edit', edit_event_path(event), class: 'dropdown-item' %>
                          <%= link_to fa_icon('trash') + ' Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
                        </div>
                      </div>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h2>Invited Events</h2>
      <div class="card">
        <div class="card-body p-0 table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col"></th>
              </tr>
            </thead>

            <tbody>
              <% @events.each do |event| %>
                <% if event.admin_id != current_user.id and event.attendances.where(user_id: current_user.id).present? and event.deadline > Time.now %>
                  <tr>
                    <td><%= event.title %></td>
                    <td><%= event.deadline.strftime("%B %d, %Y") %></td>
                    <td><%= event.deadline.strftime("%I:%M%p") %></td>
                    <td>
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Actions
                        </button>
                        <div class="dropdown-menu">
                          <%= link_to 'Show', event, class: 'dropdown-item' %>
                        </div>
                      </div>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col">
      <h2>Finished Events</h2>
      <div class="card">
        <div class="card-body p-0 table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Guessed Correctly?</th>
                <th scope="col"></th>
              </tr>
            </thead>

            <tbody>
              <% @events.each do |event| %>
                <% if event.attendances.where(user_id: current_user.id).present? and event.deadline < Time.now %>
                  <tr>
                    <td><%= event.title %></td>
                    <td><%= event.deadline.strftime("%B %d, %Y") %></td>
                    <td><%= event.deadline.strftime("%I:%M%p") %></td>
                    <td>
                    <% if event.attendances.find_by(user_id: current_user.id).user_guess_id == event.conversations.find_by(second_user_id: current_user.id).first_user_id %>
                      Si (ﾉ´ヮ`)ﾉ*: ･ﾟ
                    <% else %>
                      No 	。゜゜(´Ｏ`) ゜゜。
                    <% end %>
                    </td>
                    <td><%= link_to fa_icon('trash') + ' Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="col-md-6 offset-md-3 text-center jumbotron bg-white">
  <h1>New Event</h1>
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="jumbotron bg-white">
  <div class="row">
    <div class="col-md-4">
      <h1>
        <%= fa_icon('gift') %> <%= @event.title %>
      </h1>
      <p>
        <%= @event.description %>
      </p>
      <p>
        <h6>Price limit</h6>
        $<%= @event.price_limit %>
      </p>
      <p>
        <h6>Date</h6>
        <%= @event.deadline.strftime("%B %d, %Y") %>
      </p>
      <p>
        <h6>Hour</h6>
        <%= @event.deadline.strftime("%I:%M%p") %>
      </p>
      <h6>Share Link</h6>
      <div class="input-group">
        <input type="text" id="eventLink" class="form-control" value="http://super-secretsanta.herokuapp.com/shared_event/<%= @event.access_code_link %>">
        <div class="input-group-append">
          <button class="input-group-text" id="inputButton"><%= fa_icon('clipboard') %></button>
        </div>
      </div>
      <br><br>
      <%= link_to 'Back', events_path, class: 'btn btn-danger' %>
        <% if @event.event_chat == false and @event.admin_id == current_user.id %>
        <%= 
        link_to_if @event.attendances.where(user_id: nil).any?, 'Waiting for users', events_path, class: 'btn btn-secondary disabled' do
          link_to('Distribute Secret Santas', create_conversations_path, class: 'btn btn-dark')
        end
        %>
        <% elsif @event.event_chat == true and @event.admin_id == current_user.id %>
          <%= link_to 'Secret Santas already distributed', events_path, class: 'btn btn-secondary disabled' %>
        <% end %>
    </div>

    <div class="col-md-8">
      <div class="card">
        <div class="card-body p-0 table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Member</th>
                <th scope="col">Status</th>
              </tr>
            </thead>

            <tbody>
              <% @event.attendances.each do |member| %>
                <tr>
                  <% @users.each do |u| %>
                    <% if member.user_id == u.id %>
                      <td><%= image_tag u.image, height: 50, width: 50, class: 'rounded-lg'%></td>
                      <td><%= u.name %></td>
                    <% end %>
                  <% end %>
                    <% if member.user_id.nil? %>
                    <td><%= image_tag "new-profile.png", height: 50, class: 'rounded-lg' %></td>
                    <td>Invitado</td>
                    <td><div class="alert alert-secondary text-center">Pending</div></td>
                    <% else %>
                    <td><div class="alert alert-success text-center">Confirmed</div></td>
                    <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>