config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :attendances, only: [:edit, :update]
  resources :conversations, only: [:index, :show]
  resources :events
  resources :messages

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  get 'create_conversations/:id', controller: 'events', action: 'create_conversations', as: 'create_conversations'
  get 'shared_event/:code', controller: 'events', action: 'shared_event'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg sticky-top bg-danger py-0 px-4">
  <a class="navbar-brand" href="<%= root_path %>">
    <%= image_tag 'ss-logo.svg', alt: 'Logo', height: 40 %> 
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link text-light" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="<%= events_path %>">My Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="<%= conversations_path %>">
          Chat
          <% if user_signed_in? and (Notification.where(user_id: current_user.id, checked: false).count > 0) %>
            <span class="badge badge-light"><%= Notification.where(user_id: current_user.id, checked: false).count %></span>
          <% end %>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="<%= new_event_path %>">Create Event</a>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download" aria-expanded="true">    
        <% if user_signed_in? %>
          <%= image_tag current_user.image, height: 50, width: 50, class: 'rounded-lg'%>
        <% else %>
          Access
        <% end %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <a class="dropdown-item" href="<%= edit_user_registration_path %>"><%= fa_icon('edit') %> Edit Profile</a>
            <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE"><%= fa_icon('sign-out') %> Log Out</a>
          <% else %>
            <a class="dropdown-item" href="<%= new_user_session_path %>"><%= fa_icon('sign-in') %> Log In</a>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body class="bg-light">
    <%= render 'layouts/navbar' %>
    <div class="container mt-2">
      <%= render "shared/flash_message" %>
      <%= yield %>
    </div>
  </body>
</html>